### ISSUE TITLE
Can't exempt on subscription level

### ISSUE THREAD

**Issue by noaHochman** [globalbao/terraform-azurerm-policy-exemptions#16]
I am trying to exempt subscription from policies

**Comment by jesseloudon** [comment]
Hey there

Could you expand on your need to exempt a subscription from policies so I can understand better

As you may know, this module works at the resource group level

**Comment by abdsamad13** [comment]
I have the same need, I need to waiver a policy at management group level

any way to achieve this please ?

**Comment by jesseloudon** [comment]
Will need to uplift this module to support template deployments at higher scopes (currently supports Resource Group deployments only).

For example:
- https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/subscription_template_deployment
- https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/management_group_template_deployment
- https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/tenant_template_deployment

**Comment by jesseloudon** [comment]
# **Update: Dec 2022**
Terraform AzureRM provider now has resources available for Policy Exemptions!
I recommend utilising these for the best experience:
- https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/management_group_policy_exemption
- https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/subscription_policy_exemption
- https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/resource_group_policy_exemption
