### ISSUE TITLE
What is the minimum AzureRM provider version required for using this module?

### ISSUE THREAD

**Issue by kmcquade** [globalbao/terraform-azurerm-policy-exemptions#5]
The Cloud Guardrails tool actually requires the use of a 2.x version, so if this one requires a 3.x version of the AzureRM terraform provider, I will have to switch up the Terraform versions via `tfenv`. That's totally fine but just wanted to know. Thanks for the great work!

**Comment by jesseloudon** [comment]
> The Cloud Guardrails tool actually requires the use of a 2.x version, so if this one requires a 3.x version of the AzureRM terraform provider, I will have to switch up the Terraform versions via `tfenv`. That's totally fine but just wanted to know. Thanks for the great work!

👋 there's no min or max AzureRM provider version set in this policy exemptions module. 

I believe this means you can pin the AzureRM version to v2.x in your CloudGuardrails module and things will work even when AzureRM v3 is later released.

Hope this answers your Q
