### ISSUE TITLE
Error - module contains provider configuration

### ISSUE THREAD

**Issue by mlcooper** [globalbao/terraform-azurerm-policy-exemptions#9]
I am calling your re-usable module with a `count` parameter specified, similarly to this:
```
module "lighthouse_policy_exemption_for_daml" {
  count   = var.daml_deployed ? 1 : 0
  source  = "globalbao/policy-exemptions/azurerm"
  version = "0.1.1"
  policyExemptions = {
    exemption1 = {
      ...
    }
  }
}
```
Because your module has a `provider {}` block in it, it throws the error:
```
|Error: Module module.daml_tenant_azurepoc001.module.lighthouse_policy_exemption_for_daml contains provider configuration
│
│ Providers cannot be configured within modules using count, for_each or depends_on.
```
This is discussed by Hashicorp in detail [here](https://www.terraform.io/docs/language/modules/develop/providers.html#legacy-shared-modules-with-provider-configurations):
> Terraform v0.11 introduced the mechanisms described in earlier sections to allow passing provider configurations between modules in a structured way, and thus we explicitly recommended against writing a child module with its own provider configuration blocks.

I am specifying the `provider {}` block in my TF code that references your code. Would you consider removing the `provider {}` block from your module so that my `count` configuration will work properly?

**Comment by jesseloudon** [comment]
thanks for logging this issue! should be resolved now
